// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK6WWRS3dv5eNfgdkwft2z5OX4LpKya_k',
    appId: '1:446839569052:web:79ed40dab9fdf80034cb59',
    messagingSenderId: '446839569052',
    projectId: 'campus-connect-c7a4c',
    authDomain: 'campus-connect-c7a4c.firebaseapp.com',
    storageBucket: 'campus-connect-c7a4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAeR-BDauwG_flWc0t7TS72Z8o0WV-IFQ',
    appId: '1:446839569052:android:95959cdb5b3c4f4834cb59',
    messagingSenderId: '446839569052',
    projectId: 'campus-connect-c7a4c',
    storageBucket: 'campus-connect-c7a4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZeZz7RiHWqP678NwxMy1wTE26zUGInSk',
    appId: '1:446839569052:ios:9132728966d247be34cb59',
    messagingSenderId: '446839569052',
    projectId: 'campus-connect-c7a4c',
    storageBucket: 'campus-connect-c7a4c.appspot.com',
    iosClientId: '446839569052-gd8fa5n4ha44sjtov8pbu3km5rhpd6tq.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZeZz7RiHWqP678NwxMy1wTE26zUGInSk',
    appId: '1:446839569052:ios:9132728966d247be34cb59',
    messagingSenderId: '446839569052',
    projectId: 'campus-connect-c7a4c',
    storageBucket: 'campus-connect-c7a4c.appspot.com',
    iosClientId: '446839569052-gd8fa5n4ha44sjtov8pbu3km5rhpd6tq.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusConnect',
  );
}
